-- MySQL Script generated by MySQL Workbench
-- Wed May 22 14:55:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Infraccion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Infraccion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Infraccion` DEFAULT CHARACTER SET utf8 ;
USE `Infraccion` ;

-- -----------------------------------------------------
-- Table `Infraccion`.`Infracrtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Infraccion`.`Infracrtor` (
  `Documento` INT NOT NULL,
  `P_nombre_inf` VARCHAR(45) NOT NULL,
  `S_nombre_inf` VARCHAR(45) NULL,
  `P_apellido_int` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Infraccion`.`Agentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Infraccion`.`Agentes` (
  `idAgentes` INT NOT NULL,
  `P_Nombre_age` VARCHAR(45) NOT NULL,
  `S_nombre_age` VARCHAR(45) NULL,
  `P_apellido_age` VARCHAR(45) NOT NULL,
  `Tipo de documento_Tipo de documento` INT NOT NULL,
  PRIMARY KEY (`idAgentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Infraccion`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Infraccion`.`Vehiculo` (
  `id_Vechiculo` INT NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `Modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Vechiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Infraccion`.`comparendos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Infraccion`.`comparendos` (
  `idcomparendos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idcomparendos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Infraccion`.`infracciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Infraccion`.`infracciones` (
  `id_infracciones` INT NOT NULL AUTO_INCREMENT,
  `infracciones` VARCHAR(45) NULL,
  `comparendos_idcomparendos` INT NOT NULL,
  PRIMARY KEY (`id_infracciones`),
  INDEX `fk_infracciones_comparendos1_idx` (`comparendos_idcomparendos` ASC) ,
  CONSTRAINT `fk_infracciones_comparendos1`
    FOREIGN KEY (`comparendos_idcomparendos`)
    REFERENCES `Infraccion`.`comparendos` (`idcomparendos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Infraccion`.`infracciones_has_Agentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Infraccion`.`infracciones_has_Agentes` (
  `infracciones_idinfracciones` INT NOT NULL,
  `Agentes_idAgentes` INT NOT NULL,
  PRIMARY KEY (`infracciones_idinfracciones`, `Agentes_idAgentes`),
  INDEX `fk_infracciones_has_Agentes_Agentes1_idx` (`Agentes_idAgentes` ASC) ,
  INDEX `fk_infracciones_has_Agentes_infracciones1_idx` (`infracciones_idinfracciones` ASC) ,
  CONSTRAINT `fk_infracciones_has_Agentes_infracciones1`
    FOREIGN KEY (`infracciones_idinfracciones`)
    REFERENCES `Infraccion`.`infracciones` (`id_infracciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_infracciones_has_Agentes_Agentes1`
    FOREIGN KEY (`Agentes_idAgentes`)
    REFERENCES `Infraccion`.`Agentes` (`idAgentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Infraccion`.`infracciones_has_Infracrtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Infraccion`.`infracciones_has_Infracrtor` (
  `infracciones_idinfracciones` INT NOT NULL,
  `Infracrtor_Documento` INT NOT NULL,
  PRIMARY KEY (`infracciones_idinfracciones`, `Infracrtor_Documento`),
  INDEX `fk_infracciones_has_Infracrtor_Infracrtor1_idx` (`Infracrtor_Documento` ASC) ,
  INDEX `fk_infracciones_has_Infracrtor_infracciones1_idx` (`infracciones_idinfracciones` ASC) ,
  CONSTRAINT `fk_infracciones_has_Infracrtor_infracciones1`
    FOREIGN KEY (`infracciones_idinfracciones`)
    REFERENCES `Infraccion`.`infracciones` (`id_infracciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_infracciones_has_Infracrtor_Infracrtor1`
    FOREIGN KEY (`Infracrtor_Documento`)
    REFERENCES `Infraccion`.`Infracrtor` (`Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Infraccion`.`Vehiculo_has_infracciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Infraccion`.`Vehiculo_has_infracciones` (
  `Vehiculo_id_Vechiculo` INT NOT NULL,
  `infracciones_id_infracciones` INT NOT NULL,
  PRIMARY KEY (`Vehiculo_id_Vechiculo`, `infracciones_id_infracciones`),
  INDEX `fk_Vehiculo_has_infracciones_infracciones1_idx` (`infracciones_id_infracciones` ASC) ,
  INDEX `fk_Vehiculo_has_infracciones_Vehiculo1_idx` (`Vehiculo_id_Vechiculo` ASC) ,
  CONSTRAINT `fk_Vehiculo_has_infracciones_Vehiculo1`
    FOREIGN KEY (`Vehiculo_id_Vechiculo`)
    REFERENCES `Infraccion`.`Vehiculo` (`id_Vechiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_has_infracciones_infracciones1`
    FOREIGN KEY (`infracciones_id_infracciones`)
    REFERENCES `Infraccion`.`infracciones` (`id_infracciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Infraccion`.`Vehiculo_has_Infracrtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Infraccion`.`Vehiculo_has_Infracrtor` (
  `Vehiculo_id_Vechiculo` INT NOT NULL,
  `Infracrtor_Documento` INT NOT NULL,
  PRIMARY KEY (`Vehiculo_id_Vechiculo`, `Infracrtor_Documento`),
  INDEX `fk_Vehiculo_has_Infracrtor_Infracrtor1_idx` (`Infracrtor_Documento` ASC) ,
  INDEX `fk_Vehiculo_has_Infracrtor_Vehiculo1_idx` (`Vehiculo_id_Vechiculo` ASC) ,
  CONSTRAINT `fk_Vehiculo_has_Infracrtor_Vehiculo1`
    FOREIGN KEY (`Vehiculo_id_Vechiculo`)
    REFERENCES `Infraccion`.`Vehiculo` (`id_Vechiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_has_Infracrtor_Infracrtor1`
    FOREIGN KEY (`Infracrtor_Documento`)
    REFERENCES `Infraccion`.`Infracrtor` (`Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
