-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 23:31:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema institucion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema institucion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `institucion` DEFAULT CHARACTER SET utf8 ;
USE `institucion` ;

-- -----------------------------------------------------
-- Table `institucion`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Chat` (
  `Fecha` DATE NOT NULL,
  `Hora` TIME NULL,
  `Nom_envia` VARCHAR(45) NULL,
  `Nom_desti` VARCHAR(45) NULL,
  PRIMARY KEY (`Fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Usuario` (
  `Num_doc` INT NOT NULL,
  `Nombres` VARCHAR(45) NULL,
  `Matriculas_Num_doc` INT NOT NULL,
  `Chat_Fecha` DATE NOT NULL,
  `OBSERVADORES_Num_doc` INT NOT NULL,
  `tipo_doc` VARCHAR(45) NULL,
  `fecha_nai` DATE NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `num_tele` INT NULL,
  `Correo` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`Num_doc`, `Matriculas_Num_doc`, `Chat_Fecha`, `OBSERVADORES_Num_doc`),
  INDEX `fk_Usuario_Chat1_idx` (`Chat_Fecha` ASC) ,
  CONSTRAINT `fk_Usuario_Chat1`
    FOREIGN KEY (`Chat_Fecha`)
    REFERENCES `institucion`.`Chat` (`Fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Matriculas` (
  `Num_doc` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Grado` INT NULL,
  `jornada` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `institucion` VARCHAR(45) NULL,
  `años_realizados` INT NULL,
  `Correo_elec` INT NULL,
  `Num_tele` INT NULL,
  PRIMARY KEY (`Num_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Grados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Grados` (
  `Num_doc` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Grado` INT NULL,
  `Curso` INT NULL,
  `Matriculas_Num_doc` INT NOT NULL,
  `Nivel_educativo` VARCHAR(45) NULL,
  PRIMARY KEY (`Num_doc`, `Matriculas_Num_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Horario` (
  `Curso` INT NOT NULL,
  `Grados` INT NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  `Dia` VARCHAR(45) NULL,
  `Materis` VARCHAR(45) NULL,
  PRIMARY KEY (`Curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Cursos` (
  `Curso` INT NOT NULL,
  `Grados` INT NULL,
  `Horario_Curso` INT NOT NULL,
  PRIMARY KEY (`Curso`, `Horario_Curso`),
  INDEX `fk_Cursos_Horario1_idx` (`Horario_Curso` ASC) ,
  CONSTRAINT `fk_Cursos_Horario1`
    FOREIGN KEY (`Horario_Curso`)
    REFERENCES `institucion`.`Horario` (`Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Materias` (
  `Cursos` INT NOT NULL,
  `Grados` INT NULL,
  `Docente` VARCHAR(45) NULL,
  `Materias` VARCHAR(45) NULL,
  PRIMARY KEY (`Cursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Planillas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Planillas` (
  `Num_doc` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Grado` INT NULL,
  `Curso` INT NULL,
  PRIMARY KEY (`Num_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Notas` (
  `Num_doc` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Nota` FLOAT NULL,
  `Curso` INT NULL,
  `Id_actividades` INT NULL,
  PRIMARY KEY (`Num_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Inasistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Inasistencias` (
  `Num_doc` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Dia` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `Hora` TIME NULL,
  PRIMARY KEY (`Num_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`OBSERVADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`OBSERVADORES` (
  `Num_doc` INT NOT NULL,
  `Fecha` DATE NULL,
  `Nombre` VARCHAR(45) NULL,
  `Fecha_nac` DATE NULL,
  `Observacion` TEXT NULL,
  `Firma` VARCHAR(45) NULL,
  PRIMARY KEY (`Num_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Tareas` (
  `Curso` INT NOT NULL,
  `Grado` INT NULL,
  `Nom_tarea` VARCHAR(45) NULL,
  PRIMARY KEY (`Curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`actividades` (
  `curso` INT NOT NULL,
  `grado` INT NULL,
  `Nom_actividad` VARCHAR(45) NULL,
  `Des_actividad` VARCHAR(45) NULL,
  `Actividad` VARCHAR(45) NULL,
  PRIMARY KEY (`curso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`boletines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`boletines` (
  `Notas` INT NOT NULL,
  `grados` INT NULL,
  `CURSO` INT NULL,
  `Obser` VARCHAR(45) NULL,
  `Nota` INT NULL,
  `Logro` INT NULL,
  `Materias` INT NULL,
  `Curso` INT NULL,
  `Matricula` INT NULL,
  PRIMARY KEY (`Notas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`notificaciones` (
  `Fecha` DATE NOT NULL,
  `Notificacion` TEXT NULL,
  `Num_desti` VARCHAR(45) NULL,
  PRIMARY KEY (`Fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`publicaciones` (
  `Fecha` DATE NOT NULL,
  `notificaciones` TEXT NULL,
  `nom_anuncio` VARCHAR(45) NULL,
  `nom_desti` VARCHAR(45) NULL,
  `Usuario_Num_doc` INT NOT NULL,
  `Usuario_Matriculas_Num_doc` INT NOT NULL,
  `Usuario_Chat_Fecha` DATE NOT NULL,
  `Usuario_OBSERVADORES_Num_doc` INT NOT NULL,
  PRIMARY KEY (`Fecha`, `Usuario_Num_doc`, `Usuario_Matriculas_Num_doc`, `Usuario_Chat_Fecha`, `Usuario_OBSERVADORES_Num_doc`),
  INDEX `fk_publicaciones_Usuario1_idx` (`Usuario_Num_doc` ASC, `Usuario_Matriculas_Num_doc` ASC, `Usuario_Chat_Fecha` ASC, `Usuario_OBSERVADORES_Num_doc` ASC) ,
  CONSTRAINT `fk_publicaciones_Usuario1`
    FOREIGN KEY (`Usuario_Num_doc` , `Usuario_Matriculas_Num_doc` , `Usuario_Chat_Fecha` , `Usuario_OBSERVADORES_Num_doc`)
    REFERENCES `institucion`.`Usuario` (`Num_doc` , `Matriculas_Num_doc` , `Chat_Fecha` , `OBSERVADORES_Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Grados_has_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Grados_has_Cursos` (
  `Grados_Num_doc` INT NOT NULL,
  `Grados_Matriculas_Num_doc` INT NOT NULL,
  `Cursos_Curso` INT NOT NULL,
  PRIMARY KEY (`Grados_Num_doc`, `Grados_Matriculas_Num_doc`, `Cursos_Curso`),
  INDEX `fk_Grados_has_Cursos_Cursos1_idx` (`Cursos_Curso` ASC) ,
  INDEX `fk_Grados_has_Cursos_Grados1_idx` (`Grados_Num_doc` ASC, `Grados_Matriculas_Num_doc` ASC) ,
  CONSTRAINT `fk_Grados_has_Cursos_Grados1`
    FOREIGN KEY (`Grados_Num_doc` , `Grados_Matriculas_Num_doc`)
    REFERENCES `institucion`.`Grados` (`Num_doc` , `Matriculas_Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grados_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_Curso`)
    REFERENCES `institucion`.`Cursos` (`Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Usuario_has_Materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Usuario_has_Materias` (
  `Usuario_Num_doc` INT NOT NULL,
  `Usuario_Matriculas_Num_doc` INT NOT NULL,
  `Materias_Cursos` INT NOT NULL,
  PRIMARY KEY (`Usuario_Num_doc`, `Usuario_Matriculas_Num_doc`, `Materias_Cursos`),
  INDEX `fk_Usuario_has_Materias_Materias1_idx` (`Materias_Cursos` ASC) ,
  INDEX `fk_Usuario_has_Materias_Usuario1_idx` (`Usuario_Num_doc` ASC, `Usuario_Matriculas_Num_doc` ASC) ,
  CONSTRAINT `fk_Usuario_has_Materias_Usuario1`
    FOREIGN KEY (`Usuario_Num_doc` , `Usuario_Matriculas_Num_doc`)
    REFERENCES `institucion`.`Usuario` (`Num_doc` , `Matriculas_Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Materias_Materias1`
    FOREIGN KEY (`Materias_Cursos`)
    REFERENCES `institucion`.`Materias` (`Cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Usuario_has_Inasistencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Usuario_has_Inasistencias` (
  `Usuario_Num_doc` INT NOT NULL,
  `Usuario_Matriculas_Num_doc` INT NOT NULL,
  `Inasistencias_Num_doc` INT NOT NULL,
  PRIMARY KEY (`Usuario_Num_doc`, `Usuario_Matriculas_Num_doc`, `Inasistencias_Num_doc`),
  INDEX `fk_Usuario_has_Inasistencias_Inasistencias1_idx` (`Inasistencias_Num_doc` ASC) ,
  INDEX `fk_Usuario_has_Inasistencias_Usuario1_idx` (`Usuario_Num_doc` ASC, `Usuario_Matriculas_Num_doc` ASC) ,
  CONSTRAINT `fk_Usuario_has_Inasistencias_Usuario1`
    FOREIGN KEY (`Usuario_Num_doc` , `Usuario_Matriculas_Num_doc`)
    REFERENCES `institucion`.`Usuario` (`Num_doc` , `Matriculas_Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Inasistencias_Inasistencias1`
    FOREIGN KEY (`Inasistencias_Num_doc`)
    REFERENCES `institucion`.`Inasistencias` (`Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Materias_has_actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Materias_has_actividades` (
  `Materias_Cursos` INT NOT NULL,
  `actividades_curso` INT NOT NULL,
  PRIMARY KEY (`Materias_Cursos`, `actividades_curso`),
  INDEX `fk_Materias_has_actividades_actividades1_idx` (`actividades_curso` ASC) ,
  INDEX `fk_Materias_has_actividades_Materias1_idx` (`Materias_Cursos` ASC) ,
  CONSTRAINT `fk_Materias_has_actividades_Materias1`
    FOREIGN KEY (`Materias_Cursos`)
    REFERENCES `institucion`.`Materias` (`Cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materias_has_actividades_actividades1`
    FOREIGN KEY (`actividades_curso`)
    REFERENCES `institucion`.`actividades` (`curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`actividades_has_Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`actividades_has_Notas` (
  `actividades_curso` INT NOT NULL,
  `Notas_Num_doc` INT NOT NULL,
  PRIMARY KEY (`actividades_curso`, `Notas_Num_doc`),
  INDEX `fk_actividades_has_Notas_Notas1_idx` (`Notas_Num_doc` ASC) ,
  INDEX `fk_actividades_has_Notas_actividades1_idx` (`actividades_curso` ASC) ,
  CONSTRAINT `fk_actividades_has_Notas_actividades1`
    FOREIGN KEY (`actividades_curso`)
    REFERENCES `institucion`.`actividades` (`curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_has_Notas_Notas1`
    FOREIGN KEY (`Notas_Num_doc`)
    REFERENCES `institucion`.`Notas` (`Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Materias_has_Tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Materias_has_Tareas` (
  `Materias_Cursos` INT NOT NULL,
  `Tareas_Curso` INT NOT NULL,
  PRIMARY KEY (`Materias_Cursos`, `Tareas_Curso`),
  INDEX `fk_Materias_has_Tareas_Tareas1_idx` (`Tareas_Curso` ASC) ,
  INDEX `fk_Materias_has_Tareas_Materias1_idx` (`Materias_Cursos` ASC) ,
  CONSTRAINT `fk_Materias_has_Tareas_Materias1`
    FOREIGN KEY (`Materias_Cursos`)
    REFERENCES `institucion`.`Materias` (`Cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materias_has_Tareas_Tareas1`
    FOREIGN KEY (`Tareas_Curso`)
    REFERENCES `institucion`.`Tareas` (`Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Tareas_has_Notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Tareas_has_Notas` (
  `Tareas_Curso` INT NOT NULL,
  `Notas_Num_doc` INT NOT NULL,
  PRIMARY KEY (`Tareas_Curso`, `Notas_Num_doc`),
  INDEX `fk_Tareas_has_Notas_Notas1_idx` (`Notas_Num_doc` ASC) ,
  INDEX `fk_Tareas_has_Notas_Tareas1_idx` (`Tareas_Curso` ASC) ,
  CONSTRAINT `fk_Tareas_has_Notas_Tareas1`
    FOREIGN KEY (`Tareas_Curso`)
    REFERENCES `institucion`.`Tareas` (`Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tareas_has_Notas_Notas1`
    FOREIGN KEY (`Notas_Num_doc`)
    REFERENCES `institucion`.`Notas` (`Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Cursos_has_Planillas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Cursos_has_Planillas` (
  `Cursos_Curso` INT NOT NULL,
  `Planillas_Num_doc` INT NOT NULL,
  PRIMARY KEY (`Cursos_Curso`, `Planillas_Num_doc`),
  INDEX `fk_Cursos_has_Planillas_Planillas1_idx` (`Planillas_Num_doc` ASC) ,
  INDEX `fk_Cursos_has_Planillas_Cursos1_idx` (`Cursos_Curso` ASC) ,
  CONSTRAINT `fk_Cursos_has_Planillas_Cursos1`
    FOREIGN KEY (`Cursos_Curso`)
    REFERENCES `institucion`.`Cursos` (`Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Planillas_Planillas1`
    FOREIGN KEY (`Planillas_Num_doc`)
    REFERENCES `institucion`.`Planillas` (`Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Usuario_has_Matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Usuario_has_Matriculas` (
  `Usuario_Num_doc` INT NOT NULL,
  `Usuario_Matriculas_Num_doc` INT NOT NULL,
  `Matriculas_Num_doc` INT NOT NULL,
  PRIMARY KEY (`Usuario_Num_doc`, `Usuario_Matriculas_Num_doc`, `Matriculas_Num_doc`),
  INDEX `fk_Usuario_has_Matriculas_Matriculas1_idx` (`Matriculas_Num_doc` ASC) ,
  INDEX `fk_Usuario_has_Matriculas_Usuario1_idx` (`Usuario_Num_doc` ASC, `Usuario_Matriculas_Num_doc` ASC) ,
  CONSTRAINT `fk_Usuario_has_Matriculas_Usuario1`
    FOREIGN KEY (`Usuario_Num_doc` , `Usuario_Matriculas_Num_doc`)
    REFERENCES `institucion`.`Usuario` (`Num_doc` , `Matriculas_Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Matriculas_Matriculas1`
    FOREIGN KEY (`Matriculas_Num_doc`)
    REFERENCES `institucion`.`Matriculas` (`Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Matriculas_has_Grados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Matriculas_has_Grados` (
  `Matriculas_Num_doc` INT NOT NULL,
  `Grados_Num_doc` INT NOT NULL,
  `Grados_Matriculas_Num_doc` INT NOT NULL,
  PRIMARY KEY (`Matriculas_Num_doc`, `Grados_Num_doc`, `Grados_Matriculas_Num_doc`),
  INDEX `fk_Matriculas_has_Grados_Grados1_idx` (`Grados_Num_doc` ASC, `Grados_Matriculas_Num_doc` ASC) ,
  INDEX `fk_Matriculas_has_Grados_Matriculas1_idx` (`Matriculas_Num_doc` ASC) ,
  CONSTRAINT `fk_Matriculas_has_Grados_Matriculas1`
    FOREIGN KEY (`Matriculas_Num_doc`)
    REFERENCES `institucion`.`Matriculas` (`Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matriculas_has_Grados_Grados1`
    FOREIGN KEY (`Grados_Num_doc` , `Grados_Matriculas_Num_doc`)
    REFERENCES `institucion`.`Grados` (`Num_doc` , `Matriculas_Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Usuario_has_boletines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Usuario_has_boletines` (
  `Usuario_Num_doc` INT NOT NULL,
  `Usuario_Matriculas_Num_doc` INT NOT NULL,
  `Usuario_Chat_Fecha` DATE NOT NULL,
  `boletines_Notas` INT NOT NULL,
  PRIMARY KEY (`Usuario_Num_doc`, `Usuario_Matriculas_Num_doc`, `Usuario_Chat_Fecha`, `boletines_Notas`),
  INDEX `fk_Usuario_has_boletines_boletines1_idx` (`boletines_Notas` ASC) ,
  INDEX `fk_Usuario_has_boletines_Usuario1_idx` (`Usuario_Num_doc` ASC, `Usuario_Matriculas_Num_doc` ASC, `Usuario_Chat_Fecha` ASC) ,
  CONSTRAINT `fk_Usuario_has_boletines_Usuario1`
    FOREIGN KEY (`Usuario_Num_doc` , `Usuario_Matriculas_Num_doc` , `Usuario_Chat_Fecha`)
    REFERENCES `institucion`.`Usuario` (`Num_doc` , `Matriculas_Num_doc` , `Chat_Fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_boletines_boletines1`
    FOREIGN KEY (`boletines_Notas`)
    REFERENCES `institucion`.`boletines` (`Notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Notas_has_boletines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Notas_has_boletines` (
  `Notas_Num_doc` INT NOT NULL,
  `boletines_Notas` INT NOT NULL,
  PRIMARY KEY (`Notas_Num_doc`, `boletines_Notas`),
  INDEX `fk_Notas_has_boletines_boletines1_idx` (`boletines_Notas` ASC) ,
  INDEX `fk_Notas_has_boletines_Notas1_idx` (`Notas_Num_doc` ASC) ,
  CONSTRAINT `fk_Notas_has_boletines_Notas1`
    FOREIGN KEY (`Notas_Num_doc`)
    REFERENCES `institucion`.`Notas` (`Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_has_boletines_boletines1`
    FOREIGN KEY (`boletines_Notas`)
    REFERENCES `institucion`.`boletines` (`Notas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Rol` (
  `id_rol` INT NOT NULL,
  `Usuario_Num_doc` INT NOT NULL,
  `Usuario_Matriculas_Num_doc` INT NOT NULL,
  `Usuario_Chat_Fecha` DATE NOT NULL,
  `Usuario_OBSERVADORES_Num_doc` INT NOT NULL,
  PRIMARY KEY (`id_rol`, `Usuario_Num_doc`, `Usuario_Matriculas_Num_doc`, `Usuario_Chat_Fecha`, `Usuario_OBSERVADORES_Num_doc`),
  INDEX `fk_Rol_Usuario1_idx` (`Usuario_Num_doc` ASC, `Usuario_Matriculas_Num_doc` ASC, `Usuario_Chat_Fecha` ASC, `Usuario_OBSERVADORES_Num_doc` ASC) ,
  CONSTRAINT `fk_Rol_Usuario1`
    FOREIGN KEY (`Usuario_Num_doc` , `Usuario_Matriculas_Num_doc` , `Usuario_Chat_Fecha` , `Usuario_OBSERVADORES_Num_doc`)
    REFERENCES `institucion`.`Usuario` (`Num_doc` , `Matriculas_Num_doc` , `Chat_Fecha` , `OBSERVADORES_Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `institucion`.`Usuario_has_OBSERVADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `institucion`.`Usuario_has_OBSERVADORES` (
  `Usuario_Num_doc` INT NOT NULL,
  `Usuario_Matriculas_Num_doc` INT NOT NULL,
  `Usuario_Chat_Fecha` DATE NOT NULL,
  `Usuario_OBSERVADORES_Num_doc` INT NOT NULL,
  `OBSERVADORES_Num_doc` INT NOT NULL,
  PRIMARY KEY (`Usuario_Num_doc`, `Usuario_Matriculas_Num_doc`, `Usuario_Chat_Fecha`, `Usuario_OBSERVADORES_Num_doc`, `OBSERVADORES_Num_doc`),
  INDEX `fk_Usuario_has_OBSERVADORES_OBSERVADORES1_idx` (`OBSERVADORES_Num_doc` ASC) ,
  INDEX `fk_Usuario_has_OBSERVADORES_Usuario1_idx` (`Usuario_Num_doc` ASC, `Usuario_Matriculas_Num_doc` ASC, `Usuario_Chat_Fecha` ASC, `Usuario_OBSERVADORES_Num_doc` ASC) ,
  CONSTRAINT `fk_Usuario_has_OBSERVADORES_Usuario1`
    FOREIGN KEY (`Usuario_Num_doc` , `Usuario_Matriculas_Num_doc` , `Usuario_Chat_Fecha` , `Usuario_OBSERVADORES_Num_doc`)
    REFERENCES `institucion`.`Usuario` (`Num_doc` , `Matriculas_Num_doc` , `Chat_Fecha` , `OBSERVADORES_Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_OBSERVADORES_OBSERVADORES1`
    FOREIGN KEY (`OBSERVADORES_Num_doc`)
    REFERENCES `institucion`.`OBSERVADORES` (`Num_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
