-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 14:43:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_HEALTH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_HEALTH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_HEALTH` DEFAULT CHARACTER SET utf8 ;
USE `DB_HEALTH` ;

-- -----------------------------------------------------
-- Table `DB_HEALTH`.`PaquetesAfiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`PaquetesAfiliacion` (
  `ID_Afiliacion` INT NOT NULL AUTO_INCREMENT,
  `Num_Doc` INT NOT NULL,
  `Serv_Salud` VARCHAR(45) NULL,
  `Trabaja` VARCHAR(45) NULL,
  `Ind_Emp` VARCHAR(45) NULL,
  `Riesgo_Lab` VARCHAR(45) NULL,
  `HIjos` VARCHAR(45) NULL,
  `Cant_Hijos` INT NULL,
  `Fecha_Afi` DATE NOT NULL,
  `Valor` FLOAT NULL,
  PRIMARY KEY (`ID_Afiliacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Historial Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Historial Medico` (
  `Num_Doc` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Nacionalidad` VARCHAR(45) NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Edad` INT NULL,
  `Tipo_Sangre` VARCHAR(45) NOT NULL,
  `Alergias` VARCHAR(45) NULL,
  `Operaciones` VARCHAR(45) NULL,
  `Emfermedades` VARCHAR(45) NULL,
  `Lesiones` VARCHAR(45) NULL,
  `Novedades` VARCHAR(45) NULL,
  PRIMARY KEY (`Num_Doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Registro` (
  `Num_Doc` INT NOT NULL,
  `Tipo_Doc` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Telefono` INT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Historial Medico_Num_Doc` INT NOT NULL,
  `Roles_idRoles` INT NOT NULL,
  `Paquetes_ID_Afiliacion` INT NOT NULL,
  `Historial Medico_Num_Doc1` INT NOT NULL,
  PRIMARY KEY (`Num_Doc`, `Historial Medico_Num_Doc`, `Roles_idRoles`, `Paquetes_ID_Afiliacion`, `Historial Medico_Num_Doc1`),
  INDEX `fk_Registro_Paquetes1_idx` (`Paquetes_ID_Afiliacion` ASC) ,
  INDEX `fk_Registro_Historial Medico1_idx` (`Historial Medico_Num_Doc1` ASC) ,
  CONSTRAINT `fk_Registro_Paquetes1`
    FOREIGN KEY (`Paquetes_ID_Afiliacion`)
    REFERENCES `DB_HEALTH`.`PaquetesAfiliacion` (`ID_Afiliacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Historial Medico1`
    FOREIGN KEY (`Historial Medico_Num_Doc1`)
    REFERENCES `DB_HEALTH`.`Historial Medico` (`Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Doctores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Doctores` (
  `ID_Doctor` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Doctor` VARCHAR(45) NOT NULL,
  `Especialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Doctor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Solicitudes` (
  `ID_Solicitud` INT NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(45) NULL,
  `Tipo_Solicitud` VARCHAR(45) NULL,
  `Fecha_Solicitud` DATE NOT NULL,
  `Hora_Solicitud` TIME NULL,
  `Lugar_Solicitud` VARCHAR(45) NULL,
  `Medico` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Solicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Autorizacion_Medica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Autorizacion_Medica` (
  `ID_Autorizacion` INT NOT NULL AUTO_INCREMENT,
  `Num_Documento` INT NOT NULL,
  `Tipo_Autorizacion` VARCHAR(45) NULL,
  `Fecha_Entrega` DATE NOT NULL,
  `Fecha_Vencimiento` DATE NOT NULL,
  `Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`ID_Autorizacion`, `Historial Medico_Num_Doc`),
  INDEX `fk_Autorizacion_Medica_Historial Medico1_idx` (`Historial Medico_Num_Doc` ASC) ,
  CONSTRAINT `fk_Autorizacion_Medica_Historial Medico1`
    FOREIGN KEY (`Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Historial Medico` (`Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Copago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Copago` (
  `Ref_Pago` INT NOT NULL AUTO_INCREMENT,
  `Servicio` VARCHAR(45) NULL,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Lugar` VARCHAR(45) NULL,
  `Metodo_Pago` VARCHAR(45) NULL,
  `Valor` FLOAT NULL,
  PRIMARY KEY (`Ref_Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Roles` (
  `idRoles` INT NOT NULL,
  `Roles` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Resultados` (
  `idResultados` INT NOT NULL,
  `TipoResultado` VARCHAR(45) NULL,
  `FechaEntrega` DATE NULL,
  `Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`idResultados`, `Historial Medico_Num_Doc`),
  INDEX `fk_Resultados_Historial Medico1_idx` (`Historial Medico_Num_Doc` ASC) ,
  CONSTRAINT `fk_Resultados_Historial Medico1`
    FOREIGN KEY (`Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Historial Medico` (`Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Examenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Examenes` (
  `idExamenes` INT NOT NULL,
  `TipoExam` VARCHAR(45) NOT NULL,
  `FechaExam` DATE NULL,
  `LugarExam` VARCHAR(45) NOT NULL,
  `Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`idExamenes`, `Historial Medico_Num_Doc`),
  INDEX `fk_Examenes_Historial Medico1_idx` (`Historial Medico_Num_Doc` ASC) ,
  CONSTRAINT `fk_Examenes_Historial Medico1`
    FOREIGN KEY (`Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Historial Medico` (`Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Recetas_Medicinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Recetas_Medicinas` (
  `idRecetas_Medicinas` INT NOT NULL,
  `TipoReceta` VARCHAR(45) NOT NULL,
  `Medicamento` VARCHAR(45) NOT NULL,
  `FechaEntrega` DATE NULL,
  `TipoEntrega` VARCHAR(45) NOT NULL,
  `PlazoEntrega` VARCHAR(45) NULL,
  `Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`idRecetas_Medicinas`, `Historial Medico_Num_Doc`),
  INDEX `fk_Recetas_Medicinas_Historial Medico1_idx` (`Historial Medico_Num_Doc` ASC) ,
  CONSTRAINT `fk_Recetas_Medicinas_Historial Medico1`
    FOREIGN KEY (`Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Historial Medico` (`Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Citas` (
  `idCitas` INT NOT NULL,
  `TipoCita` VARCHAR(45) NOT NULL,
  `FechaCita` DATE NULL,
  `LugarCita` VARCHAR(45) NOT NULL,
  `Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`idCitas`, `Historial Medico_Num_Doc`),
  INDEX `fk_Citas_Historial Medico1_idx` (`Historial Medico_Num_Doc` ASC) ,
  CONSTRAINT `fk_Citas_Historial Medico1`
    FOREIGN KEY (`Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Historial Medico` (`Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Publicaciones` (
  `idPublicaciones` INT NOT NULL,
  `Publicacion` VARCHAR(45) NULL,
  `FechaPublicacion` DATE NOT NULL,
  `Detalles` VARCHAR(45) NULL,
  `Registro_Num_Doc` INT NOT NULL,
  `Registro_Historial Medico_Num_Doc` INT NOT NULL,
  `Registro_Roles_idRoles` INT NOT NULL,
  PRIMARY KEY (`idPublicaciones`, `Registro_Num_Doc`, `Registro_Historial Medico_Num_Doc`, `Registro_Roles_idRoles`),
  INDEX `fk_Publicaciones_Registro_idx` (`Registro_Num_Doc` ASC, `Registro_Historial Medico_Num_Doc` ASC, `Registro_Roles_idRoles` ASC) ,
  CONSTRAINT `fk_Publicaciones_Registro`
    FOREIGN KEY (`Registro_Num_Doc` , `Registro_Historial Medico_Num_Doc` , `Registro_Roles_idRoles`)
    REFERENCES `DB_HEALTH`.`Registro` (`Num_Doc` , `Historial Medico_Num_Doc` , `Roles_idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Consultorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Consultorios` (
  `NumeroConsultorios` INT NOT NULL,
  `Piso` INT NULL,
  `Sede` VARCHAR(45) NULL,
  PRIMARY KEY (`NumeroConsultorios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`PagoAfiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`PagoAfiliacion` (
  `PaquetesAfiliacion_ID_Afiliacion` INT NOT NULL,
  PRIMARY KEY (`PaquetesAfiliacion_ID_Afiliacion`),
  CONSTRAINT `fk_PagoAfiliacion_PaquetesAfiliacion1`
    FOREIGN KEY (`PaquetesAfiliacion_ID_Afiliacion`)
    REFERENCES `DB_HEALTH`.`PaquetesAfiliacion` (`ID_Afiliacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Optometria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Optometria` (
  `idOptometria` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOptometria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Odontologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Odontologia` (
  `idOdontologia` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOdontologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`General`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`General` (
  `idGeneral` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGeneral`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Roles_has_Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Roles_has_Registro` (
  `Roles_idRoles` INT NOT NULL,
  `Registro_Num_Doc` INT NOT NULL,
  `Registro_Historial Medico_Num_Doc` INT NOT NULL,
  `Registro_Roles_idRoles` INT NOT NULL,
  PRIMARY KEY (`Roles_idRoles`, `Registro_Num_Doc`, `Registro_Historial Medico_Num_Doc`, `Registro_Roles_idRoles`),
  INDEX `fk_Roles_has_Registro_Registro1_idx` (`Registro_Num_Doc` ASC, `Registro_Historial Medico_Num_Doc` ASC, `Registro_Roles_idRoles` ASC) ,
  INDEX `fk_Roles_has_Registro_Roles1_idx` (`Roles_idRoles` ASC) ,
  CONSTRAINT `fk_Roles_has_Registro_Roles1`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `DB_HEALTH`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Roles_has_Registro_Registro1`
    FOREIGN KEY (`Registro_Num_Doc` , `Registro_Historial Medico_Num_Doc` , `Registro_Roles_idRoles`)
    REFERENCES `DB_HEALTH`.`Registro` (`Num_Doc` , `Historial Medico_Num_Doc` , `Roles_idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Solicitudes_has_Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Solicitudes_has_Registro` (
  `Solicitudes_ID_Solicitud` INT NOT NULL,
  `Registro_Num_Doc` INT NOT NULL,
  `Registro_Historial Medico_Num_Doc` INT NOT NULL,
  `Registro_Roles_idRoles` INT NOT NULL,
  PRIMARY KEY (`Solicitudes_ID_Solicitud`, `Registro_Num_Doc`, `Registro_Historial Medico_Num_Doc`, `Registro_Roles_idRoles`),
  INDEX `fk_Solicitudes_has_Registro_Registro1_idx` (`Registro_Num_Doc` ASC, `Registro_Historial Medico_Num_Doc` ASC, `Registro_Roles_idRoles` ASC) ,
  INDEX `fk_Solicitudes_has_Registro_Solicitudes1_idx` (`Solicitudes_ID_Solicitud` ASC) ,
  CONSTRAINT `fk_Solicitudes_has_Registro_Solicitudes1`
    FOREIGN KEY (`Solicitudes_ID_Solicitud`)
    REFERENCES `DB_HEALTH`.`Solicitudes` (`ID_Solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitudes_has_Registro_Registro1`
    FOREIGN KEY (`Registro_Num_Doc` , `Registro_Historial Medico_Num_Doc` , `Registro_Roles_idRoles`)
    REFERENCES `DB_HEALTH`.`Registro` (`Num_Doc` , `Historial Medico_Num_Doc` , `Roles_idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Historial Medico_has_Doctores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Historial Medico_has_Doctores` (
  `Historial Medico_Num_Doc` INT NOT NULL,
  `Doctores_ID_Doctor` INT NOT NULL,
  PRIMARY KEY (`Historial Medico_Num_Doc`, `Doctores_ID_Doctor`),
  INDEX `fk_Historial Medico_has_Doctores_Doctores1_idx` (`Doctores_ID_Doctor` ASC) ,
  INDEX `fk_Historial Medico_has_Doctores_Historial Medico1_idx` (`Historial Medico_Num_Doc` ASC) ,
  CONSTRAINT `fk_Historial Medico_has_Doctores_Historial Medico1`
    FOREIGN KEY (`Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Historial Medico` (`Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historial Medico_has_Doctores_Doctores1`
    FOREIGN KEY (`Doctores_ID_Doctor`)
    REFERENCES `DB_HEALTH`.`Doctores` (`ID_Doctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Consultorios_has_Doctores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Consultorios_has_Doctores` (
  `Consultorios_NumeroConsultorios` INT NOT NULL,
  `Doctores_ID_Doctor` INT NOT NULL,
  PRIMARY KEY (`Consultorios_NumeroConsultorios`, `Doctores_ID_Doctor`),
  INDEX `fk_Consultorios_has_Doctores_Doctores1_idx` (`Doctores_ID_Doctor` ASC) ,
  INDEX `fk_Consultorios_has_Doctores_Consultorios1_idx` (`Consultorios_NumeroConsultorios` ASC) ,
  CONSTRAINT `fk_Consultorios_has_Doctores_Consultorios1`
    FOREIGN KEY (`Consultorios_NumeroConsultorios`)
    REFERENCES `DB_HEALTH`.`Consultorios` (`NumeroConsultorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consultorios_has_Doctores_Doctores1`
    FOREIGN KEY (`Doctores_ID_Doctor`)
    REFERENCES `DB_HEALTH`.`Doctores` (`ID_Doctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Citas_has_Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Citas_has_Solicitudes` (
  `Citas_idCitas` INT NOT NULL,
  `Solicitudes_ID_Solicitud` INT NOT NULL,
  PRIMARY KEY (`Citas_idCitas`, `Solicitudes_ID_Solicitud`),
  INDEX `fk_Citas_has_Solicitudes_Solicitudes1_idx` (`Solicitudes_ID_Solicitud` ASC) ,
  INDEX `fk_Citas_has_Solicitudes_Citas1_idx` (`Citas_idCitas` ASC) ,
  CONSTRAINT `fk_Citas_has_Solicitudes_Citas1`
    FOREIGN KEY (`Citas_idCitas`)
    REFERENCES `DB_HEALTH`.`Citas` (`idCitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citas_has_Solicitudes_Solicitudes1`
    FOREIGN KEY (`Solicitudes_ID_Solicitud`)
    REFERENCES `DB_HEALTH`.`Solicitudes` (`ID_Solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Examenes_has_Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Examenes_has_Solicitudes` (
  `Examenes_idExamenes` INT NOT NULL,
  `Solicitudes_ID_Solicitud` INT NOT NULL,
  PRIMARY KEY (`Examenes_idExamenes`, `Solicitudes_ID_Solicitud`),
  INDEX `fk_Examenes_has_Solicitudes_Solicitudes1_idx` (`Solicitudes_ID_Solicitud` ASC) ,
  INDEX `fk_Examenes_has_Solicitudes_Examenes1_idx` (`Examenes_idExamenes` ASC) ,
  CONSTRAINT `fk_Examenes_has_Solicitudes_Examenes1`
    FOREIGN KEY (`Examenes_idExamenes`)
    REFERENCES `DB_HEALTH`.`Examenes` (`idExamenes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Examenes_has_Solicitudes_Solicitudes1`
    FOREIGN KEY (`Solicitudes_ID_Solicitud`)
    REFERENCES `DB_HEALTH`.`Solicitudes` (`ID_Solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Recetas_Medicinas_has_Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Recetas_Medicinas_has_Citas` (
  `Recetas_Medicinas_idRecetas_Medicinas` INT NOT NULL,
  `Citas_idCitas` INT NOT NULL,
  PRIMARY KEY (`Recetas_Medicinas_idRecetas_Medicinas`, `Citas_idCitas`),
  INDEX `fk_Recetas_Medicinas_has_Citas_Citas1_idx` (`Citas_idCitas` ASC) ,
  INDEX `fk_Recetas_Medicinas_has_Citas_Recetas_Medicinas1_idx` (`Recetas_Medicinas_idRecetas_Medicinas` ASC) ,
  CONSTRAINT `fk_Recetas_Medicinas_has_Citas_Recetas_Medicinas1`
    FOREIGN KEY (`Recetas_Medicinas_idRecetas_Medicinas`)
    REFERENCES `DB_HEALTH`.`Recetas_Medicinas` (`idRecetas_Medicinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recetas_Medicinas_has_Citas_Citas1`
    FOREIGN KEY (`Citas_idCitas`)
    REFERENCES `DB_HEALTH`.`Citas` (`idCitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Odontologia_has_Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Odontologia_has_Citas` (
  `Odontologia_idOdontologia` INT NOT NULL,
  `Citas_idCitas` INT NOT NULL,
  `Citas_Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`Odontologia_idOdontologia`, `Citas_idCitas`, `Citas_Historial Medico_Num_Doc`),
  INDEX `fk_Odontologia_has_Citas_Citas1_idx` (`Citas_idCitas` ASC, `Citas_Historial Medico_Num_Doc` ASC) ,
  INDEX `fk_Odontologia_has_Citas_Odontologia1_idx` (`Odontologia_idOdontologia` ASC) ,
  CONSTRAINT `fk_Odontologia_has_Citas_Odontologia1`
    FOREIGN KEY (`Odontologia_idOdontologia`)
    REFERENCES `DB_HEALTH`.`Odontologia` (`idOdontologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Odontologia_has_Citas_Citas1`
    FOREIGN KEY (`Citas_idCitas` , `Citas_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Citas` (`idCitas` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`General_has_Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`General_has_Citas` (
  `General_idGeneral` INT NOT NULL,
  `Citas_idCitas` INT NOT NULL,
  `Citas_Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`General_idGeneral`, `Citas_idCitas`, `Citas_Historial Medico_Num_Doc`),
  INDEX `fk_General_has_Citas_Citas1_idx` (`Citas_idCitas` ASC, `Citas_Historial Medico_Num_Doc` ASC) ,
  INDEX `fk_General_has_Citas_General1_idx` (`General_idGeneral` ASC) ,
  CONSTRAINT `fk_General_has_Citas_General1`
    FOREIGN KEY (`General_idGeneral`)
    REFERENCES `DB_HEALTH`.`General` (`idGeneral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_General_has_Citas_Citas1`
    FOREIGN KEY (`Citas_idCitas` , `Citas_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Citas` (`idCitas` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Optometria_has_Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Optometria_has_Citas` (
  `Optometria_idOptometria` INT NOT NULL,
  `Citas_idCitas` INT NOT NULL,
  `Citas_Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`Optometria_idOptometria`, `Citas_idCitas`, `Citas_Historial Medico_Num_Doc`),
  INDEX `fk_Optometria_has_Citas_Citas1_idx` (`Citas_idCitas` ASC, `Citas_Historial Medico_Num_Doc` ASC) ,
  INDEX `fk_Optometria_has_Citas_Optometria1_idx` (`Optometria_idOptometria` ASC) ,
  CONSTRAINT `fk_Optometria_has_Citas_Optometria1`
    FOREIGN KEY (`Optometria_idOptometria`)
    REFERENCES `DB_HEALTH`.`Optometria` (`idOptometria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Optometria_has_Citas_Citas1`
    FOREIGN KEY (`Citas_idCitas` , `Citas_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Citas` (`idCitas` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Autorizacion_Medica_has_Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Autorizacion_Medica_has_Citas` (
  `Autorizacion_Medica_ID_Autorizacion` INT NOT NULL,
  `Citas_idCitas` INT NOT NULL,
  `Citas_Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`Autorizacion_Medica_ID_Autorizacion`, `Citas_idCitas`, `Citas_Historial Medico_Num_Doc`),
  INDEX `fk_Autorizacion_Medica_has_Citas_Citas1_idx` (`Citas_idCitas` ASC, `Citas_Historial Medico_Num_Doc` ASC) ,
  INDEX `fk_Autorizacion_Medica_has_Citas_Autorizacion_Medica1_idx` (`Autorizacion_Medica_ID_Autorizacion` ASC) ,
  CONSTRAINT `fk_Autorizacion_Medica_has_Citas_Autorizacion_Medica1`
    FOREIGN KEY (`Autorizacion_Medica_ID_Autorizacion`)
    REFERENCES `DB_HEALTH`.`Autorizacion_Medica` (`ID_Autorizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autorizacion_Medica_has_Citas_Citas1`
    FOREIGN KEY (`Citas_idCitas` , `Citas_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Citas` (`idCitas` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Odontologia_has_Examenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Odontologia_has_Examenes` (
  `Odontologia_idOdontologia` INT NOT NULL,
  `Examenes_idExamenes` INT NOT NULL,
  `Examenes_Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`Odontologia_idOdontologia`, `Examenes_idExamenes`, `Examenes_Historial Medico_Num_Doc`),
  INDEX `fk_Odontologia_has_Examenes_Examenes1_idx` (`Examenes_idExamenes` ASC, `Examenes_Historial Medico_Num_Doc` ASC) ,
  INDEX `fk_Odontologia_has_Examenes_Odontologia1_idx` (`Odontologia_idOdontologia` ASC) ,
  CONSTRAINT `fk_Odontologia_has_Examenes_Odontologia1`
    FOREIGN KEY (`Odontologia_idOdontologia`)
    REFERENCES `DB_HEALTH`.`Odontologia` (`idOdontologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Odontologia_has_Examenes_Examenes1`
    FOREIGN KEY (`Examenes_idExamenes` , `Examenes_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Examenes` (`idExamenes` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Optometria_has_Examenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Optometria_has_Examenes` (
  `Optometria_idOptometria` INT NOT NULL,
  `Examenes_idExamenes` INT NOT NULL,
  `Examenes_Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`Optometria_idOptometria`, `Examenes_idExamenes`, `Examenes_Historial Medico_Num_Doc`),
  INDEX `fk_Optometria_has_Examenes_Examenes1_idx` (`Examenes_idExamenes` ASC, `Examenes_Historial Medico_Num_Doc` ASC) ,
  INDEX `fk_Optometria_has_Examenes_Optometria1_idx` (`Optometria_idOptometria` ASC) ,
  CONSTRAINT `fk_Optometria_has_Examenes_Optometria1`
    FOREIGN KEY (`Optometria_idOptometria`)
    REFERENCES `DB_HEALTH`.`Optometria` (`idOptometria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Optometria_has_Examenes_Examenes1`
    FOREIGN KEY (`Examenes_idExamenes` , `Examenes_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Examenes` (`idExamenes` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Resultados_has_Examenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Resultados_has_Examenes` (
  `Resultados_idResultados` INT NOT NULL,
  `Examenes_idExamenes` INT NOT NULL,
  `Examenes_Historial Medico_Num_Doc` INT NOT NULL,
  PRIMARY KEY (`Resultados_idResultados`, `Examenes_idExamenes`, `Examenes_Historial Medico_Num_Doc`),
  INDEX `fk_Resultados_has_Examenes_Examenes1_idx` (`Examenes_idExamenes` ASC, `Examenes_Historial Medico_Num_Doc` ASC) ,
  INDEX `fk_Resultados_has_Examenes_Resultados1_idx` (`Resultados_idResultados` ASC) ,
  CONSTRAINT `fk_Resultados_has_Examenes_Resultados1`
    FOREIGN KEY (`Resultados_idResultados`)
    REFERENCES `DB_HEALTH`.`Resultados` (`idResultados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Resultados_has_Examenes_Examenes1`
    FOREIGN KEY (`Examenes_idExamenes` , `Examenes_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Examenes` (`idExamenes` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Recetas_Medicinas_has_Copago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Recetas_Medicinas_has_Copago` (
  `Recetas_Medicinas_idRecetas_Medicinas` INT NOT NULL,
  `Recetas_Medicinas_Historial Medico_Num_Doc` INT NOT NULL,
  `Copago_Ref_Pago` INT NOT NULL,
  PRIMARY KEY (`Recetas_Medicinas_idRecetas_Medicinas`, `Recetas_Medicinas_Historial Medico_Num_Doc`, `Copago_Ref_Pago`),
  INDEX `fk_Recetas_Medicinas_has_Copago_Copago1_idx` (`Copago_Ref_Pago` ASC) ,
  INDEX `fk_Recetas_Medicinas_has_Copago_Recetas_Medicinas1_idx` (`Recetas_Medicinas_idRecetas_Medicinas` ASC, `Recetas_Medicinas_Historial Medico_Num_Doc` ASC) ,
  CONSTRAINT `fk_Recetas_Medicinas_has_Copago_Recetas_Medicinas1`
    FOREIGN KEY (`Recetas_Medicinas_idRecetas_Medicinas` , `Recetas_Medicinas_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Recetas_Medicinas` (`idRecetas_Medicinas` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recetas_Medicinas_has_Copago_Copago1`
    FOREIGN KEY (`Copago_Ref_Pago`)
    REFERENCES `DB_HEALTH`.`Copago` (`Ref_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Citas_has_Copago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Citas_has_Copago` (
  `Citas_idCitas` INT NOT NULL,
  `Citas_Historial Medico_Num_Doc` INT NOT NULL,
  `Copago_Ref_Pago` INT NOT NULL,
  PRIMARY KEY (`Citas_idCitas`, `Citas_Historial Medico_Num_Doc`, `Copago_Ref_Pago`),
  INDEX `fk_Citas_has_Copago_Copago1_idx` (`Copago_Ref_Pago` ASC) ,
  INDEX `fk_Citas_has_Copago_Citas1_idx` (`Citas_idCitas` ASC, `Citas_Historial Medico_Num_Doc` ASC) ,
  CONSTRAINT `fk_Citas_has_Copago_Citas1`
    FOREIGN KEY (`Citas_idCitas` , `Citas_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Citas` (`idCitas` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citas_has_Copago_Copago1`
    FOREIGN KEY (`Copago_Ref_Pago`)
    REFERENCES `DB_HEALTH`.`Copago` (`Ref_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_HEALTH`.`Autorizacion_Medica_has_Copago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_HEALTH`.`Autorizacion_Medica_has_Copago` (
  `Autorizacion_Medica_ID_Autorizacion` INT NOT NULL,
  `Autorizacion_Medica_Historial Medico_Num_Doc` INT NOT NULL,
  `Copago_Ref_Pago` INT NOT NULL,
  PRIMARY KEY (`Autorizacion_Medica_ID_Autorizacion`, `Autorizacion_Medica_Historial Medico_Num_Doc`, `Copago_Ref_Pago`),
  INDEX `fk_Autorizacion_Medica_has_Copago_Copago1_idx` (`Copago_Ref_Pago` ASC) ,
  INDEX `fk_Autorizacion_Medica_has_Copago_Autorizacion_Medica1_idx` (`Autorizacion_Medica_ID_Autorizacion` ASC, `Autorizacion_Medica_Historial Medico_Num_Doc` ASC) ,
  CONSTRAINT `fk_Autorizacion_Medica_has_Copago_Autorizacion_Medica1`
    FOREIGN KEY (`Autorizacion_Medica_ID_Autorizacion` , `Autorizacion_Medica_Historial Medico_Num_Doc`)
    REFERENCES `DB_HEALTH`.`Autorizacion_Medica` (`ID_Autorizacion` , `Historial Medico_Num_Doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autorizacion_Medica_has_Copago_Copago1`
    FOREIGN KEY (`Copago_Ref_Pago`)
    REFERENCES `DB_HEALTH`.`Copago` (`Ref_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
